name: release.yml
on:
  push:
    tags:
      - '*.*.*'
permissions:
    contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build 26.1
        run: |
          ./gradlew stonecutterSwitchTo26.1 --no-daemon --stacktrace
          ./gradlew :26.1:clean :26.1:build --no-daemon --stacktrace --no-build-cache

      - name: Build 26.2
        run: |
          ./gradlew stonecutterSwitchTo26.2 --no-daemon --stacktrace
          ./gradlew :26.2:clean :26.2:build --no-daemon --stacktrace --no-build-cache

      - name: Create Draft Release
        run: |
          gh release create "${{ github.ref_name }}" \
            versions/26.1/build/libs/*.jar \
            versions/26.2/build/libs/*.jar \
            --draft \
            --title "SkyblockCollectionTracker ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}